### ISSUE TITLE
[Fix] RecentViewed 화면에서 CartItem을 지우고, Cart화면으로 되돌아가면 Exception 발생

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#138]
## 📚 To-do

- [x] RecentViewed 화면에서 CartItem을 지우고, Cart화면으로 되돌아가면 Exception 발생
- [x] CartItem 제거시 Exception 발생

## 📆 실제 작업 시간

08.23 02:00 - 02:20

**Comment by wjchoi96** [comment]
RecentVIewed 화면에 Cart State 가 적용되지않아 적용해보았는데, RecentViewed화면에서 CartItem을 제거하고, Cart화면으로 되돌아가면 Exception 발생
```
2022-08-23 01:27:29.953 9534-9534/com.woowahan.banchan E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woowahan.banchan, PID: 9534
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionCartFooterViewHolder{5595d6b position=3 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{7208183 VFED..... ......ID 0,0-1080,1668 #7f080184 app:id/rv_cart}, adapter:com.woowahan.banchan.ui.adapter.DefaultCartAdapter@e9f3f00, layout:androidx.recyclerview.widget.LinearLayoutManager@9000339, context:com.woowahan.banchan.ui.cart.CartActivity@49f1a96
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4085)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
        at android.view.View.layout(View.java:23203)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3749)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3205)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
2022-08-23 01:27:29.953 9534-9534/com.woowahan.banchan E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by wjchoi96** [comment]
또한, RecentViewed화면에서 CartItem을 제거하자 에러 발생
해당 에러도 디버깅이 필요할듯으로 보인다
```
2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 1811 SQLITE_CONSTRAINT_TRIGGER)
2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:892)
2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.dao.BanchanDao_Impl.removeBanchanItems(BanchanDao_Impl.java:79)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.datasource.CartDataSourceImpl$removeCartItem$2.invokeSuspend(CartDataSourceImpl.kt:31)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.datasource.CartDataSourceImpl$removeCartItem$2.invoke(Unknown Source:8)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.datasource.CartDataSourceImpl$removeCartItem$2.invoke(Unknown Source:4)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.repository.CartRepositoryImpl$removeCartItem$2.invokeSuspend(CartRepositoryImpl.kt:45)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.repository.CartRepositoryImpl$removeCartItem$2.invoke(Unknown Source:8)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.repository.CartRepositoryImpl$removeCartItem$2.invoke(Unknown Source:4)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by wjchoi96** [comment]
**RecentViewed화면에서 CartItem을 제거하자 에러 발생**

RecentViewed 와 Cart가 같은 ItemTable을 공유하고있기때문에 발생한 Exception
ItemTable을 제거시도할때, 참조되고있다면 제거되지 않도록 제약을 걸어두었는데, 해당 제약이 잘 동작함으로 인해 Exception이 발생하고,
해당 Exception이 전달되는것 뿐이다.

해당 Exception은 중간에 catch해서 전달 안되도록 해야겠다.

**Comment by wjchoi96** [comment]
> 또한, RecentViewed화면에서 CartItem을 제거하자 에러 발생 해당 에러도 디버깅이 필요할듯으로 보인다
> 
> 이전에도 브랜치 전환시에 가끔 발생했던 Exception인것으로 보아, 아마 브랜치 병합간에 문제가 발생한듯 보인다
> 
> ```
> 2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 1811 SQLITE_CONSTRAINT_TRIGGER)
> 2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
> 2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:892)
> 2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
> 2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
> 2022-08-23 01:29:50.402 9686-9686/com.woowahan.banchan W/System.err:     at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.dao.BanchanDao_Impl.removeBanchanItems(BanchanDao_Impl.java:79)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.datasource.CartDataSourceImpl$removeCartItem$2.invokeSuspend(CartDataSourceImpl.kt:31)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.datasource.CartDataSourceImpl$removeCartItem$2.invoke(Unknown Source:8)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.datasource.CartDataSourceImpl$removeCartItem$2.invoke(Unknown Source:4)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.repository.CartRepositoryImpl$removeCartItem$2.invokeSuspend(CartRepositoryImpl.kt:45)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.repository.CartRepositoryImpl$removeCartItem$2.invoke(Unknown Source:8)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at com.woowahan.data.repository.CartRepositoryImpl$removeCartItem$2.invoke(Unknown Source:4)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 2022-08-23 01:29:50.403 9686-9686/com.woowahan.banchan W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> ```

**RecentViewed화면에서 CartItem을 제거하자 에러 발생**

RecentViewed 와 Cart가 같은 ItemTable을 공유하고있기때문에 발생한 Exception
ItemTable을 제거시도할때, 참조되고있다면 제거되지 않도록 제약을 걸어두었는데, 해당 제약이 잘 동작함으로 인해 Exception이 발생하고,
해당 Exception이 전달되는것 뿐이다.

해당 Exception은 중간에 catch해서 전달 안되도록 해야겠다.
`android.database.sqlite.SQLiteConstraintException` + `Throwable message contain 1811` 인 경우, 성공 처리로 반환하도록 처리

https://www.sqlite.org/rescode.html#constraint_trigger
(1811) SQLITE_CONSTRAINT_TRIGGER
SQLITE_CONSTRAINT_TRIGGER 오류 코드는 [트리거](https://www.sqlite.org/lang_createtrigger.html) 내의 [RAISE 함수](https://www.sqlite.org/lang_createtrigger.html#raise) 가 실행 되어 SQL 문이 중단 되었음을 나타내는 [SQLITE_CONSTRAINT 에 대한 ](https://www.sqlite.org/rescode.html#constraint)[확장 오류 코드](https://www.sqlite.org/rescode.html#pve) 입니다

**Comment by YM-Byun** [comment]
```
    fun updateList(newList: List<CartListItemModel>) {
        CoroutineScope(Dispatchers.Default).launch {
            val diffCallback = CartListModelDiffUtilCallback(cartList, newList)
            val diffRes = DiffUtil.calculateDiff(diffCallback)
            withContext(Dispatchers.Main) {
                cartList = newList
                diffRes.dispatchUpdatesTo(this@DefaultCartAdapter)
            }
        }
    }
```

기존의 `updateList`메소드를 분석하다 이상한 점을 발견했다. 일단 미지의 이유로 CartList가 업데이트가 되면 `Activity`에서 `emit`이 2번 되었다. 

 그리고 디버깅을 하려고 `diffRes` 를 계산 하는 line에 break point를 걸었더니 다음과 같은 일이 일어났다.
1. 첫 번째 emit 시, `diffCallBack`의 `oldList`와 `newList`는 예전 리스트, 새 리스트가 들어왔다. 
2. 두 번째 emit 시에 문제가 생겼다. `diffCallBack`의 생성자로 들어온  `cartList`( `oldList`)가 첫 번째 emit의 `newList`가 들어와야하는데 첫 번째 emit의  `oldList`가 들어왔다. 
3. `diffCallBack`으로 1번 째 emit의 `oldList`가 들어온 직후, Adapter의 `cartList`를 보니 `newList`로 바뀌어있었다.

 디버깅을 좀 더 해보니 다음과 같은 일도 발생했다.
1. `diffRes` 계산 부분에 break point를 걸었을 땐 `diffCallBack`에 갱신되지 않은 `cartList`가 들어왔다
2. 하지만 `diffCallBack` 계산 부분에 `break point`를 걸었을 땐 `cartList`에 갱신된 값이 들어가 있었고, 그 후 계속 실행하니 정상작동이 되었다.

그래서 내린 결론이 어떤 이유로 인해 `cartList`가 업데이트 되기 전에 `diffCallback`을 계산해서 갱신된 `cartList`와 계산된 `diffCallback`사이에 괴리가 생긴 것이었다.

해결방법을 찾아보려고 다양한 시도를 해보다가 문득 `cartList = newList` 를 `Dispatchers.Main`안에서 계산을 한 부분이 마음에 걸렸다. `diffCallback`은 `Dispatchers.Default`에서 하는데 갱신은 `Main`에서 해서 시간차이가 생기는 것이 아닐까 싶어서 해당 부분을 `Default`안으로 옮겨보니 해결되었다..!
